version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_NAME: slim_db
      DB_USER: root
      DB_PASS: secret
    extra_hosts:
      - "db:host-gateway"
    networks:
      - my_network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: slim_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - my_network

volumes:
  mysql-data:

networks:
  my_network:
