version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-cli
    volumes:
      - .:/var/www/html
    ports:
      - 8080:8000
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_DATABASE=slim
      - DB_USERNAME=user
      - DB_PASSWORD=password
    command: php -S 0.0.0.0:8000 -t /var/www/html/public

  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=slim
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

volumes:
  mysql_data:
